// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalProject.Models;

namespace finalProject.Migrations
{
    [DbContext(typeof(panelDbContext))]
    partial class panelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("finalProject.Models.Device", b =>
                {
                    b.Property<int>("deviceID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("deviceCPUmodel");

                    b.Property<int>("deviceCPUspeed");

                    b.Property<int>("deviceDisk");

                    b.Property<string>("deviceIP");

                    b.Property<string>("deviceMACaddress");

                    b.Property<string>("deviceName");

                    b.Property<string>("deviceOwner");

                    b.Property<int>("deviceRAM");

                    b.Property<string>("deviceSituation");

                    b.HasKey("deviceID");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("finalProject.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userEmail");

                    b.Property<string>("userName");

                    b.Property<string>("userPassword");

                    b.Property<string>("userRole");

                    b.Property<string>("userSurname");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
